global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'raf_grafana_app'
    static_configs:
      - targets: ['host.docker.internal:5335'] # hard-coded port matches launchSettings.json
